/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FFormIdRouteImport } from './routes/f.$formId'
import { Route as FormsFormIdEditRouteImport } from './routes/forms.$formId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdEditRoute = FormsFormIdEditRouteImport.update({
  id: '/forms/$formId/edit',
  path: '/forms/$formId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f/$formId': typeof FFormIdRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f/$formId': typeof FFormIdRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f/$formId': typeof FFormIdRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f/$formId' | '/forms/$formId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f/$formId' | '/forms/$formId/edit'
  id: '__root__' | '/' | '/f/$formId' | '/forms/$formId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FFormIdRoute: typeof FFormIdRoute
  FormsFormIdEditRoute: typeof FormsFormIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/edit': {
      id: '/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof FormsFormIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FFormIdRoute: FFormIdRoute,
  FormsFormIdEditRoute: FormsFormIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
