// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createForm = `-- name: CreateForm :one
INSERT INTO forms (title, description, fields)
VALUES ($1, $2, $3)
RETURNING id, title, description, fields, created_at, updated_at
`

type CreateFormParams struct {
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Fields      json.RawMessage `json:"fields"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, createForm,
		arg.Title,
		arg.Description,
		arg.Fields,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms
WHERE id = $1
`

func (q *Queries) DeleteForm(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteForm, id)
	return err
}

const getForm = `-- name: GetForm :one
SELECT id, title, description, fields, created_at, updated_at FROM forms
WHERE id = $1
`

func (q *Queries) GetForm(ctx context.Context, id uuid.UUID) (Form, error) {
	row := q.db.QueryRowContext(ctx, getForm, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listForms = `-- name: ListForms :many
SELECT id, title, description, fields, created_at, updated_at FROM forms
ORDER BY created_at DESC
`

func (q *Queries) ListForms(ctx context.Context) ([]Form, error) {
	rows, err := q.db.QueryContext(ctx, listForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Fields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET title = $1,
    description = $2,
    fields = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, title, description, fields, created_at, updated_at
`

type UpdateFormParams struct {
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Fields      json.RawMessage `json:"fields"`
	ID          uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, updateForm,
		arg.Title,
		arg.Description,
		arg.Fields,
		arg.ID,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
