// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Form struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Fields      json.RawMessage `json:"fields"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Submission struct {
	ID          uuid.UUID       `json:"id"`
	FormID      uuid.UUID       `json:"form_id"`
	Responses   json.RawMessage `json:"responses"`
	SubmittedAt time.Time       `json:"submitted_at"`
}
