// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countSubmissionsByForm = `-- name: CountSubmissionsByForm :one
SELECT COUNT(*) FROM submissions
WHERE form_id = $1
`

func (q *Queries) CountSubmissionsByForm(ctx context.Context, formID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubmissionsByForm, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (form_id, responses)
VALUES ($1, $2)
RETURNING id, form_id, responses, submitted_at
`

type CreateSubmissionParams struct {
	FormID    uuid.UUID       `json:"form_id"`
	Responses json.RawMessage `json:"responses"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission, arg.FormID, arg.Responses)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Responses,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, form_id, responses, submitted_at FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Responses,
		&i.SubmittedAt,
	)
	return i, err
}

const listSubmissionsByForm = `-- name: ListSubmissionsByForm :many
SELECT id, form_id, responses, submitted_at FROM submissions
WHERE form_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListSubmissionsByForm(ctx context.Context, formID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Responses,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
